version: "3"

services:

  coordinator:
    build:
      context: .
      dockerfile: Dockerfile.server
    command: /server/configs/default.json
    ports:
      - "2000:2000"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    command: Alice
    stdin_open: true
    environment:
      - SERVER_HOST=coordinator
      - SERVER_PORT=2000
    ports:
      - "10001:10001"
    depends_on:
      - coordinator
    links:
      - coordinator
