# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serialization/schemas/perf_test_case.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*serialization/schemas/perf_test_case.proto\"\xb6\x01\n\rTPerfTestCase\x12\x12\n\nstring_key\x18\x01 \x01(\t\x12\x0f\n\x07int_key\x18\x02 \x01(\x03\x12\x11\n\tfloat_key\x18\x03 \x01(\x02\x12\x11\n\tarray_key\x18\x04 \x03(\t\x12+\n\x07map_key\x18\x05 \x03(\x0b\x32\x1a.TPerfTestCase.MapKeyEntry\x1a-\n\x0bMapKeyEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'serialization.schemas.perf_test_case_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TPERFTESTCASE_MAPKEYENTRY._options = None
  _TPERFTESTCASE_MAPKEYENTRY._serialized_options = b'8\001'
  _TPERFTESTCASE._serialized_start=47
  _TPERFTESTCASE._serialized_end=229
  _TPERFTESTCASE_MAPKEYENTRY._serialized_start=184
  _TPERFTESTCASE_MAPKEYENTRY._serialized_end=229
# @@protoc_insertion_point(module_scope)
